# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.entry.listener:
        class: AppBundle\EventListener\EntryManagementListener
        arguments: ["%entry_limit_per_ip_username_combo%", "%entry_limit_per_ip%"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
